"""Author inspectable therapeutic programs for in-vivo immune-cell engineering."""

__version__ = "0.1.0.dev10"

from cellweave.ir.payload import (
    PayloadFeature,
    PayloadMolecule,
    PayloadReference,
    PayloadRegion,
    PayloadReview,
    PayloadSource,
)
from cellweave.verification.payload import (
    PayloadDiagnostic,
    PayloadResult,
    check_payload,
    payload_dependencies,
)
from cellweave.semantics.molecular_behavior import (
    MolecularEvidence,
    MolecularImplementationContract,
    MolecularInputBinding,
    MolecularParameter,
    MolecularResponseBinding,
)
from cellweave.verification.molecular_behavior import (
    MolecularBehaviorDiagnostic,
    MolecularBehaviorResult,
    check_molecular_implementation,
    molecular_behavior_dependencies,
)

from cellweave.verification.exploration import (
    AdversarialConfig,
    BooleanContactConfig,
    BooleanObservation,
    ExplorationReport,
    FailureSignature,
    HistoryCase,
    ReductionResult,
    enumerate_boolean_histories,
    explore_boolean_histories,
    generate_adversarial_histories,
    reduce_counterexample,
)
from cellweave.artifacts.manifest import (
    BuildManifest,
    ReferenceBuildRequest,
    RunMetadata,
)
from cellweave.compiler.reference import (
    ReferencePackage,
    build_reference_package,
    prepare_reference_build,
    publish_reference_package,
    verify_reference_package,
)
from cellweave.artifacts.sequences import (
    SequenceExport,
    export_reference_sequence,
    verify_sequence_export,
)
from cellweave.backends.dna import emit_dna_cds
from cellweave.backends.rna import emit_rna_cds
from cellweave.compiler.molecular import MolecularBuild, run_molecular_pipeline
from cellweave.ir.molecular import (
    EncodingChange,
    EncodingEvidencePolicy,
    EncodingPolicy,
    FeatureStatus,
    MolecularArtifact,
    MolecularRecord,
    TranslationPolicy,
    canonical_sequence_sha256,
)
from cellweave.verification.molecular import (
    MolecularCheck,
    MolecularDiagnostic,
    MolecularResult,
    check_molecular,
)
from cellweave.compiler.construct import ConstructBuild, run_construct_pipeline
from cellweave.ir.construct import (
    ComponentPlacement,
    ConstructCandidate,
    ConstructDependency,
    ConstructFeature,
    ConstructJunction,
    ConstructMolecule,
    ConstructReference,
    ConstructRequest,
    LayoutEvidencePolicy,
    RegulatoryRelationship,
    SequenceRange,
)
from cellweave.synthesis.construct import (
    generate_construct,
    prepare_reference_construct,
)
from cellweave.verification.construct import ConstructResult, check_construct

from cellweave.compiler.components import (
    ComponentBuild,
    check_component_assembly,
    run_component_pipeline,
)
from cellweave.ir.component_assembly import ComponentAssembly
from cellweave.ir.component_contracts import (
    ComponentRecord,
    DependencyRequirement,
    ParameterProvenance,
    PinnedIdentity,
    ProvidedCapability,
    ResourceReservation,
    SequenceReferenceMetadata,
)
from cellweave.ir.composition import (
    CompositionInstance,
    CompositionRequest,
    Connection,
    DependencyBinding,
    LifecycleInterval,
    Provider,
    ResourceBinding,
    ResourcePool,
)
from cellweave.registry.components import (
    ComponentRegistry,
    RegistryLock,
    SelectionRequest,
)
from cellweave.registry.reference_components import (
    ReferenceSelection,
    adapt_reference_component,
)
from cellweave.semantics.component_contracts import (
    OperatingDomain as ComponentOperatingDomain,
    PortContract,
    ValueDomain,
)
from cellweave.verification.components import CompositionResult, check_composition

from cellweave.compiler.behavior import lower_to_behavior, verify_lowering
from cellweave.compiler.request import (
    BindingMetadata,
    BuildRequest,
    ElaborationProvenance,
    RealizationRequest,
)
from cellweave.compiler.synthetic import SyntheticBuild, run_synthetic_pipeline
from cellweave.synthesis.synthetic import (
    SyntheticCandidate,
    SyntheticGeneratorConfig,
    generate_synthetic,
    check_synthetic_candidate,
)
from cellweave.compiler.workflow import (
    BuildProfile,
    DesignChoice,
    RealizationPlan,
    compile,
    plan,
)
from cellweave.errors import (
    BehaviorError,
    CellWeaveError,
    EvaluationError,
    LoweringError,
    LoweringVerificationError,
    NonConvergenceError,
    StateConflictError,
    UnsupportedBehaviorError,
    CompilationUnavailableError,
    DefinitionError,
    ScopeError,
    SerializationError,
    TypeMismatchError,
)
from cellweave.frontend.api import (
    Action,
    CellProgram,
    Channel,
    ContactScope,
    Controller,
    EnvironmentScope,
    ExternalScope,
    Goal,
    InternalScope,
    Memory,
    Rule,
    RuleBuilder,
    Scope,
    Secretion,
    State,
    Therapy,
)
from cellweave.frontend.expressions import (
    Condition,
    ControlPort,
    Event,
    Expr,
    Parameter,
    Quantity,
    Signal,
    SpatialSignal,
    at_least,
)
from cellweave.frontend.signatures import Signature, signature
from cellweave.ir.intent import IntentNode, IntentProgram, SourceLocation
from cellweave.ir.behavior import BehaviorNode, BehaviorProgram
from cellweave.ir.mechanism import MechanismNode, MechanismProgram
from cellweave.models.synthetic import ModelInputFrame, ModelTrace, run_model
from cellweave.semantics.contracts import (
    BehaviorRequirement,
    LoweringReport,
    PreservationCheck,
)
from cellweave.semantics.evaluator import (
    ActionRequest,
    EvaluationFrame,
    EvaluationResult,
    EventOccurrence,
    InputFrame,
    SignalSample,
    evaluate,
)
from cellweave.semantics.context import HumanTargetContext, PayloadFormat, TargetContext
from cellweave.semantics.human_target import (
    HumanHostDependency,
    HumanOperatingCondition,
    HumanTargetContract,
    TargetClaim,
    TargetEvidence,
)
from cellweave.semantics.realization import (
    BehaviorContract,
    InputDomain,
    Observable,
    OperatingDomain,
    ResponseRequirement,
)
from cellweave.semantics.types import (
    Concentration,
    Curve,
    Duration,
    Interval,
    Level,
    ProductionRate,
    ScalarLiteral,
    SurfaceDensity,
    TypeSpec,
)
from cellweave.verification.evidence import (
    CheckDiagnostic,
    CheckOutcome,
    CheckResult,
    Counterexample,
    DependencySnapshot,
    EvidenceKind,
    FreshnessReport,
    RequirementCoverage,
)
from cellweave.verification.realization import (
    InputBinding,
    ObservationMap,
    OutputBinding,
    check_realization,
    realization_dependencies,
)

__all__ = [
    "HumanTargetContext",
    "HumanTargetContract",
    "HumanHostDependency",
    "HumanOperatingCondition",
    "TargetClaim",
    "TargetEvidence",
    "PayloadFeature",
    "PayloadMolecule",
    "PayloadReference",
    "PayloadRegion",
    "PayloadReview",
    "PayloadSource",
    "PayloadDiagnostic",
    "PayloadResult",
    "check_payload",
    "payload_dependencies",
    "MolecularEvidence",
    "MolecularImplementationContract",
    "MolecularInputBinding",
    "MolecularParameter",
    "MolecularResponseBinding",
    "MolecularBehaviorDiagnostic",
    "MolecularBehaviorResult",
    "check_molecular_implementation",
    "molecular_behavior_dependencies",
    "AdversarialConfig",
    "BooleanContactConfig",
    "BooleanObservation",
    "ExplorationReport",
    "FailureSignature",
    "HistoryCase",
    "ReductionResult",
    "enumerate_boolean_histories",
    "explore_boolean_histories",
    "generate_adversarial_histories",
    "reduce_counterexample",
    "BuildManifest",
    "ReferenceBuildRequest",
    "ReferencePackage",
    "RunMetadata",
    "build_reference_package",
    "prepare_reference_build",
    "publish_reference_package",
    "verify_reference_package",
    "EncodingChange",
    "EncodingEvidencePolicy",
    "EncodingPolicy",
    "FeatureStatus",
    "MolecularArtifact",
    "MolecularBuild",
    "MolecularCheck",
    "MolecularDiagnostic",
    "MolecularRecord",
    "MolecularResult",
    "SequenceExport",
    "TranslationPolicy",
    "canonical_sequence_sha256",
    "check_molecular",
    "emit_dna_cds",
    "emit_rna_cds",
    "export_reference_sequence",
    "run_molecular_pipeline",
    "verify_sequence_export",
    "ComponentPlacement",
    "ConstructBuild",
    "ConstructCandidate",
    "ConstructDependency",
    "ConstructFeature",
    "ConstructJunction",
    "ConstructMolecule",
    "ConstructReference",
    "ConstructRequest",
    "ConstructResult",
    "LayoutEvidencePolicy",
    "RegulatoryRelationship",
    "SequenceRange",
    "check_construct",
    "generate_construct",
    "prepare_reference_construct",
    "run_construct_pipeline",
    "ComponentAssembly",
    "ComponentBuild",
    "ComponentOperatingDomain",
    "ComponentRecord",
    "ComponentRegistry",
    "CompositionInstance",
    "CompositionRequest",
    "CompositionResult",
    "Connection",
    "DependencyBinding",
    "DependencyRequirement",
    "LifecycleInterval",
    "ParameterProvenance",
    "PinnedIdentity",
    "PortContract",
    "ProvidedCapability",
    "Provider",
    "ReferenceSelection",
    "RegistryLock",
    "ResourceBinding",
    "ResourcePool",
    "ResourceReservation",
    "SelectionRequest",
    "SequenceReferenceMetadata",
    "ValueDomain",
    "adapt_reference_component",
    "check_component_assembly",
    "check_composition",
    "run_component_pipeline",
    "SyntheticBuild",
    "SyntheticCandidate",
    "SyntheticGeneratorConfig",
    "generate_synthetic",
    "check_synthetic_candidate",
    "run_synthetic_pipeline",
    "BindingMetadata",
    "BuildRequest",
    "ElaborationProvenance",
    "RealizationRequest",
    "BehaviorContract",
    "CheckDiagnostic",
    "CheckOutcome",
    "CheckResult",
    "Counterexample",
    "DependencySnapshot",
    "EvidenceKind",
    "FreshnessReport",
    "RequirementCoverage",
    "InputBinding",
    "InputDomain",
    "MechanismNode",
    "MechanismProgram",
    "ModelInputFrame",
    "ModelTrace",
    "Observable",
    "ObservationMap",
    "OperatingDomain",
    "OutputBinding",
    "ResponseRequirement",
    "check_realization",
    "realization_dependencies",
    "run_model",
    "ActionRequest",
    "BehaviorError",
    "BehaviorNode",
    "BehaviorProgram",
    "BehaviorRequirement",
    "EvaluationError",
    "EvaluationFrame",
    "EvaluationResult",
    "EventOccurrence",
    "InputFrame",
    "LoweringError",
    "LoweringReport",
    "LoweringVerificationError",
    "NonConvergenceError",
    "PreservationCheck",
    "SignalSample",
    "StateConflictError",
    "UnsupportedBehaviorError",
    "evaluate",
    "lower_to_behavior",
    "verify_lowering",
    "Action",
    "BuildProfile",
    "CellProgram",
    "CellWeaveError",
    "Channel",
    "CompilationUnavailableError",
    "Concentration",
    "Condition",
    "ContactScope",
    "ControlPort",
    "Controller",
    "Curve",
    "DefinitionError",
    "DesignChoice",
    "Duration",
    "EnvironmentScope",
    "Event",
    "Expr",
    "ExternalScope",
    "Goal",
    "IntentNode",
    "IntentProgram",
    "InternalScope",
    "Interval",
    "Level",
    "Memory",
    "Parameter",
    "PayloadFormat",
    "ProductionRate",
    "Quantity",
    "RealizationPlan",
    "Rule",
    "RuleBuilder",
    "ScalarLiteral",
    "Scope",
    "ScopeError",
    "Secretion",
    "SerializationError",
    "Signal",
    "Signature",
    "SourceLocation",
    "SpatialSignal",
    "State",
    "SurfaceDensity",
    "TargetContext",
    "Therapy",
    "TypeMismatchError",
    "TypeSpec",
    "at_least",
    "compile",
    "plan",
    "signature",
]
