"""Author inspectable therapeutic programs for in-vivo immune-cell engineering."""

__version__ = "0.1.0.dev4"

from cellweave.compiler.behavior import lower_to_behavior, verify_lowering
from cellweave.compiler.request import (
    BindingMetadata,
    BuildRequest,
    ElaborationProvenance,
    RealizationRequest,
)
from cellweave.compiler.synthetic import SyntheticBuild, run_synthetic_pipeline
from cellweave.synthesis.synthetic import (
    SyntheticCandidate,
    SyntheticGeneratorConfig,
    generate_synthetic,
    check_synthetic_candidate,
)
from cellweave.compiler.workflow import (
    BuildProfile,
    DesignChoice,
    RealizationPlan,
    compile,
    plan,
)
from cellweave.errors import (
    BehaviorError,
    CellWeaveError,
    EvaluationError,
    LoweringError,
    LoweringVerificationError,
    NonConvergenceError,
    StateConflictError,
    UnsupportedBehaviorError,
    CompilationUnavailableError,
    DefinitionError,
    ScopeError,
    SerializationError,
    TypeMismatchError,
)
from cellweave.frontend.api import (
    Action,
    CellProgram,
    Channel,
    ContactScope,
    Controller,
    EnvironmentScope,
    ExternalScope,
    Goal,
    InternalScope,
    Memory,
    Rule,
    RuleBuilder,
    Scope,
    Secretion,
    State,
    Therapy,
)
from cellweave.frontend.expressions import (
    Condition,
    ControlPort,
    Event,
    Expr,
    Parameter,
    Quantity,
    Signal,
    SpatialSignal,
    at_least,
)
from cellweave.frontend.signatures import Signature, signature
from cellweave.ir.intent import IntentNode, IntentProgram, SourceLocation
from cellweave.ir.behavior import BehaviorNode, BehaviorProgram
from cellweave.ir.mechanism import MechanismNode, MechanismProgram
from cellweave.models.synthetic import ModelInputFrame, ModelTrace, run_model
from cellweave.semantics.contracts import (
    BehaviorRequirement,
    LoweringReport,
    PreservationCheck,
)
from cellweave.semantics.evaluator import (
    ActionRequest,
    EvaluationFrame,
    EvaluationResult,
    EventOccurrence,
    InputFrame,
    SignalSample,
    evaluate,
)
from cellweave.semantics.context import PayloadFormat, TargetContext
from cellweave.semantics.realization import (
    BehaviorContract,
    InputDomain,
    Observable,
    OperatingDomain,
    ResponseRequirement,
)
from cellweave.semantics.types import (
    Concentration,
    Curve,
    Duration,
    Interval,
    Level,
    ProductionRate,
    ScalarLiteral,
    SurfaceDensity,
    TypeSpec,
)
from cellweave.verification.evidence import (
    CheckDiagnostic,
    CheckOutcome,
    CheckResult,
    Counterexample,
    DependencySnapshot,
    EvidenceKind,
    FreshnessReport,
    RequirementCoverage,
)
from cellweave.verification.realization import (
    InputBinding,
    ObservationMap,
    OutputBinding,
    check_realization,
    realization_dependencies,
)

__all__ = [
    "SyntheticBuild",
    "SyntheticCandidate",
    "SyntheticGeneratorConfig",
    "generate_synthetic",
    "check_synthetic_candidate",
    "run_synthetic_pipeline",
    "BindingMetadata",
    "BuildRequest",
    "ElaborationProvenance",
    "RealizationRequest",
    "BehaviorContract",
    "CheckDiagnostic",
    "CheckOutcome",
    "CheckResult",
    "Counterexample",
    "DependencySnapshot",
    "EvidenceKind",
    "FreshnessReport",
    "RequirementCoverage",
    "InputBinding",
    "InputDomain",
    "MechanismNode",
    "MechanismProgram",
    "ModelInputFrame",
    "ModelTrace",
    "Observable",
    "ObservationMap",
    "OperatingDomain",
    "OutputBinding",
    "ResponseRequirement",
    "check_realization",
    "realization_dependencies",
    "run_model",
    "ActionRequest",
    "BehaviorError",
    "BehaviorNode",
    "BehaviorProgram",
    "BehaviorRequirement",
    "EvaluationError",
    "EvaluationFrame",
    "EvaluationResult",
    "EventOccurrence",
    "InputFrame",
    "LoweringError",
    "LoweringReport",
    "LoweringVerificationError",
    "NonConvergenceError",
    "PreservationCheck",
    "SignalSample",
    "StateConflictError",
    "UnsupportedBehaviorError",
    "evaluate",
    "lower_to_behavior",
    "verify_lowering",
    "Action",
    "BuildProfile",
    "CellProgram",
    "CellWeaveError",
    "Channel",
    "CompilationUnavailableError",
    "Concentration",
    "Condition",
    "ContactScope",
    "ControlPort",
    "Controller",
    "Curve",
    "DefinitionError",
    "DesignChoice",
    "Duration",
    "EnvironmentScope",
    "Event",
    "Expr",
    "ExternalScope",
    "Goal",
    "IntentNode",
    "IntentProgram",
    "InternalScope",
    "Interval",
    "Level",
    "Memory",
    "Parameter",
    "PayloadFormat",
    "ProductionRate",
    "Quantity",
    "RealizationPlan",
    "Rule",
    "RuleBuilder",
    "ScalarLiteral",
    "Scope",
    "ScopeError",
    "Secretion",
    "SerializationError",
    "Signal",
    "Signature",
    "SourceLocation",
    "SpatialSignal",
    "State",
    "SurfaceDensity",
    "TargetContext",
    "Therapy",
    "TypeMismatchError",
    "TypeSpec",
    "at_least",
    "compile",
    "plan",
    "signature",
]
