"""Independent language authority and unchanged v0.1 wire compatibility."""
import copy
from contextlib import redirect_stderr
from dataclasses import replace
import hashlib
import io
import json
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

from tools import generate_policy_wire_schema as language


# Retained from the pre-migration checked native shape table and frozen corpus.
# Neither pin is generated by the new schema tool.
V01_SHAPES = "750841bdf2f398721252d4e7a79a7ebc9a55838eb856b0230c260179a53172b4"
V01_CORPUS = "c4c7f3251c882ed739eb3b733bb0eea0cd2965470e02e6293196e114b0a3aded"


class PolicyLanguageSpecificationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.specification = language.read_specification()
        cls.source = (language.ROOT / language.MODEL).read_text()

    def test_independent_authority_reproduces_every_existing_native_shape(self):
        rendered = language.render(self.specification)
        payload = rendered[rendered.index("type shape ="):]
        self.assertEqual(hashlib.sha256(payload.encode()).hexdigest(), V01_SHAPES)
        self.assertEqual(rendered, (language.ROOT / language.TARGET).read_text())
        self.assertIn('let language_sha256 = "' + language.specification_digest(self.specification), rendered)
        self.assertNotIn("model_sha256", rendered)
        self.assertEqual(len(self.specification["$defs"]), 45)

    def test_render_does_not_read_or_import_the_python_sdk(self):
        expected = language.render(self.specification)
        imported = {name for name in sys.modules if name.startswith("biocompiler")}
        with patch.object(language, "ROOT", Path("/missing-sdk")):
            self.assertEqual(language.render(self.specification), expected)
        self.assertEqual(imported, {name for name in sys.modules if name.startswith("biocompiler")})

    def test_python_is_checked_inertly_even_with_executable_source(self):
        with tempfile.TemporaryDirectory() as directory:
            marker = Path(directory) / "must-not-exist"
            source = self.source + f'\nopen({str(marker)!r}, "w").write("executed")\nraise RuntimeError("executed")\n'
            imported = {name for name in sys.modules if name.startswith("biocompiler")}
            language.check_python_conformance(self.specification, source)
            self.assertFalse(marker.exists())
            self.assertEqual(imported, {name for name in sys.modules if name.startswith("biocompiler")})

    def test_comments_and_nonwire_methods_are_not_language_authority(self):
        changed = self.source.replace('"""Base for immutable, data-only declarations."""', '"""A client implementation."""')
        language.check_python_conformance(self.specification, changed)
        self.assertEqual(language.render(self.specification), (language.ROOT / language.TARGET).read_text())

    def test_python_type_enum_field_and_alias_drift_is_rejected(self):
        mutations = [
            ('    id: str\n', '    id: int\n'),
            ('Literal["availability", "observation", "logical"]', 'Literal["availability", "observation", "wall"]'),
            ('    question: str\n', '    question: str\n    extra: str\n'),
            ('    question: str\n', ''),
            ('Declaration: TypeAlias = Role | Subject', 'Declaration: TypeAlias = Subject'),
            ('Document: TypeAlias = PolicyDraft | PolicyProgram | BuildRequest', 'Document: TypeAlias = PolicyProgram | BuildRequest'),
            ('    kind: str\n', '    kind: resolve_type()\n'),
            ('    kind: str\n', '    kind: "UnknownForwardType"\n'),
            ('class Ref(Record):', 'class Ref(Record, OtherBase):'),
            ('class Subject(Record):', 'class Subject(Ref):'),
            ('class Ref(Record):\n    id: str', 'class Ref(Record):\n    id: str\n    id: str'),
        ]
        for before, after in mutations:
            with self.subTest(after=after):
                self.assertIn(before, self.source)
                with self.assertRaises(language.LanguageSchemaError):
                    language.check_python_conformance(self.specification, self.source.replace(before, after, 1))

    def test_duplicate_and_reassigned_client_definitions_are_rejected(self):
        additions = [
            '\nclass Ref(Record):\n    id: str\n',
            '\nDeclaration: TypeAlias = Role\n',
            '\nRef = object\n',
            '\nRef: type = object\n',
            '\nRef: TypeAlias = int\n',
            '\ndef Ref(): pass\n',
            '\nRef, x = object, None\n',
            '\nif True:\n    Ref = object\n',
            '\nfrom elsewhere import Ref\n',
            '\nfrom elsewhere import *\n',
            '\nPROFILE: str = "changed"\n',
            '\nDeclaration = object\n',
            '\n@dataclass(frozen=True)\nclass Hidden(Ref):\n    extra: str\n',
        ]
        for addition in additions:
            with self.subTest(addition=addition), self.assertRaises(language.LanguageSchemaError):
                language.check_python_conformance(self.specification, self.source + addition)

    def test_implicit_inherited_field_and_nonfrozen_record_are_rejected(self):
        for source in (
            self.source.replace('class Record:\n', 'class Record:\n    hidden: str\n'),
            self.source.replace('@dataclass(frozen=True)\nclass Ref', '@dataclass(frozen=False)\nclass Ref'),
        ):
            with self.subTest(source=source[:40]), self.assertRaises(language.LanguageSchemaError):
                language.check_python_conformance(self.specification, source)

    def test_specification_edit_does_not_silently_redefine_python(self):
        changed = copy.deepcopy(self.specification)
        changed["$defs"]["Clock"]["properties"]["basis"]["enum"].append("wall")
        self.assertNotEqual(language.render(changed), language.render(self.specification))
        with self.assertRaisesRegex(language.LanguageSchemaError, "Clock"):
            language.check_python_conformance(changed, self.source)

    def test_source_drift_cannot_regenerate_native_or_specification(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            for path in (language.SPECIFICATION, language.MODEL, language.TARGET):
                target = root / path
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes((language.ROOT / path).read_bytes())
            (root / language.MODEL).write_text(self.source.replace('    id: str\n', '    id: int\n', 1))
            originals = {path: (root / path).read_bytes() for path in (language.SPECIFICATION, language.TARGET)}
            for arguments in ([], ["--check"]):
                with patch.object(language, "ROOT", root), patch.object(sys, "argv", ["schema", *arguments]), redirect_stderr(io.StringIO()):
                    self.assertEqual(language.main(), 1)
            self.assertEqual(originals, {path: (root / path).read_bytes() for path in originals})

    def test_closed_shapes_reject_added_keywords_defaults_and_bad_references(self):
        mutations = [
            lambda s: s.update(extra=True),
            lambda s: s["$defs"]["Ref"].update(default={}),
            lambda s: s["$defs"]["Ref"].update(additionalProperties=True),
            lambda s: s["$defs"]["Ref"]["required"].remove("id"),
            lambda s: s["$defs"]["Ref"]["required"].append("id"),
            lambda s: s["$defs"]["Ref"]["properties"]["id"].update(default="x"),
            lambda s: s["$defs"]["Ref"]["properties"]["$type"].update(const="Role"),
            lambda s: s["$defs"]["Role"]["properties"]["population"]["anyOf"][0].update({"$ref": "#/$defs/Missing"}),
            lambda s: s["$defs"]["Clock"]["properties"]["basis"]["enum"].append("logical"),
            lambda s: s["$defs"]["Clock"]["properties"]["basis"]["enum"].append(True),
            lambda s: s["$defs"]["Clock"]["properties"]["basis"]["enum"].append("délai"),
            lambda s: s["x-policy-language"].update(revision=True),
        ]
        for index, mutate in enumerate(mutations):
            candidate = copy.deepcopy(self.specification)
            mutate(candidate)
            with self.subTest(index=index), self.assertRaises(language.LanguageSchemaError):
                language.validate(candidate)

    def test_duplicate_json_keys_and_noninteger_numbers_are_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "schema.json"
            for raw in ('{"$defs":{},"$defs":{}}', '{"x":NaN}', '{"x":1.0}', '{"x":Infinity}'):
                path.write_text(raw)
                with self.subTest(raw=raw), self.assertRaises(language.LanguageSchemaError):
                    language.read_specification(path)

    def test_specification_size_depth_and_work_are_bounded(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "schema.json"
            path.write_bytes(b" " * (language.MAX_SPEC_BYTES + 1))
            with self.assertRaisesRegex(language.LanguageSchemaError, "byte limit"):
                language.read_specification(path)
        deep = "leaf"
        for _ in range(language.MAX_SPEC_DEPTH + 1):
            deep = [deep]
        with self.assertRaisesRegex(language.LanguageSchemaError, "traversal limit"):
            language.validate(deep)
        with patch.object(language, "MAX_SPEC_NODES", 10), self.assertRaisesRegex(language.LanguageSchemaError, "traversal limit"):
            language.validate(self.specification)

    def test_sdk_schema_export_is_a_conforming_client(self):
        from biocompiler.policy.serialization import schema
        exported = schema()
        expected = {key: value for key, value in self.specification.items() if key not in ("$id", "x-policy-language")}
        self.assertEqual(exported, expected)

    def test_existing_twenty_four_documents_retain_exact_bytes_and_identities(self):
        from biocompiler.policy.serialization import document_digest, dumps, from_data
        raw = (language.ROOT / "core/test/data/policy_documents_v01.json").read_bytes()
        self.assertEqual(hashlib.sha256(raw).hexdigest(), V01_CORPUS)
        cases = json.loads(raw)["cases"]
        self.assertEqual(len(cases), 24)
        for case in cases:
            with self.subTest(name=case["name"], kind=case["kind"]):
                document = from_data(case["document"])
                wire = json.dumps(case["document"], ensure_ascii=False, sort_keys=True, separators=(",", ":"))
                self.assertEqual(dumps(document, indent=None), wire)
                self.assertEqual(hashlib.sha256(wire.encode()).hexdigest(), case["artifact_digest"])
                self.assertEqual(document_digest(document), case["document_digest"])

    def test_defaults_never_authorize_omitted_wire_fields(self):
        from biocompiler.policy import model as m
        from biocompiler.policy.serialization import from_data, to_data, PolicySerializationError
        wire = to_data(m.Role("executor", ()))
        self.assertIs(wire["lineage_role"], False)
        self.assertIsNone(wire["population"])
        for field in ("lineage_role", "population"):
            with self.subTest(field=field), self.assertRaises(PolicySerializationError):
                from_data({key: value for key, value in wire.items() if key != field})

    def test_canonical_rules_preserve_order_and_exclude_only_named_metadata(self):
        from biocompiler.policy import model as m
        from biocompiler.policy.serialization import document_digest, dumps, to_data
        a, b = m.Subject("a", "cell", "stable"), m.Subject("b", "cell", "stable")
        program = m.PolicyProgram("unicode_é", m.SemanticBundle("semantics", "1"), (a, b),
                                  (m.SourceSpan("a", "α.py", 1),))
        wire = to_data(program)
        canonical = json.dumps(wire, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        self.assertEqual(dumps(program, indent=None), canonical)
        self.assertIn("α.py", canonical)
        self.assertNotEqual(document_digest(program), document_digest(replace(program, declarations=(b, a))))
        relocated = replace(program, source_map=(m.SourceSpan("a", "β.py", 12),))
        self.assertEqual(document_digest(program), document_digest(relocated))
        # The nested source map is removed by the same identity projection.
        # Patch only to_data: the arbitrary graph tests the projection contract,
        # not acceptance of an invalid request or extra provenance wire field.
        nested = {"keep": [{"source_map": ["a"], "provenance": "old", "value": "source_map"}]}
        with patch("biocompiler.policy.serialization.to_data", return_value=nested):
            expected = hashlib.sha256(b'{"keep":[{"value":"source_map"}]}').hexdigest()
            self.assertEqual(document_digest(program), expected)

    def test_decimal_authoring_normalization_and_native_canonical_boundary_are_distinct(self):
        from biocompiler.policy import model as m
        from biocompiler.policy.serialization import dumps, from_data, to_data
        unit = m.Unit("s", "time", "duration")
        for spelling, canonical in (("1.500", "1.5"), ("1e2", "100"), ("-0", "0")):
            with self.subTest(spelling=spelling):
                quantity = m.Quantity(spelling, unit)
                self.assertEqual(quantity.amount, canonical)
                self.assertEqual(from_data(to_data(quantity)), quantity)
                self.assertIn('"amount":"' + canonical + '"', dumps(quantity, indent=None))
        with self.assertRaises(TypeError):
            m.Quantity(0.1, unit)


if __name__ == "__main__":
    unittest.main()
