(* Generated by tools/generate_policy_wire_schema.py from the versioned language schema.
   Closed representation data only; no semantic acceptance authority. *)
let language_sha256 = "6b95b71f552041f5465d56f35a43439aee7b23c7c4aa2152716a6f967bd9fb30"
type shape = String | Integer | Boolean | Null | Literals of string list
  | Record of string | Many of shape | Tuple of shape list | Union of shape list
let records = [
  "Arbitration", [
    "mode", Literals ["exclusive"; "priority"; "concurrent"; "nondeterministic"];
    "tie", Literals ["reject"; "declared_order"; "nondeterministic"];
    "write_conflict", Literals ["reject"; "identical_only"; "contract"];
    "preemption", Literals ["forbidden"; "request_cancel"; "contract"];
    "fairness", Literals ["none"; "weak"; "strong"];
    "order", Many (String);
    "contract", Union [Record "DefinitionRef"; Null]];
  "Argument", [
    "name", String;
    "value", Record "Expr"];
  "Assignment", [
    "state", Record "Ref";
    "value", Record "Expr"];
  "AssuranceRequest", [
    "requirements", Many (String);
    "level", Literals ["structural"; "bounded"; "proof"];
    "horizon", Union [Record "Quantity"; Literals ["unbounded_requested"]];
    "assumptions", Many (String);
    "tolerances", Many (Record "Argument")];
  "BackendCapabilities", [
    "backend_id", String;
    "version", String;
    "profiles", Many (String);
    "features", Many (String)];
  "BuildRequest", [
    "program", Record "PolicyProgram";
    "deployment", Record "Deployment";
    "implementations", Record "ImplementationCatalogLock";
    "assurance", Record "AssuranceRequest";
    "profile", String];
  "CapabilityAssessment", [
    "backend_id", String;
    "backend_version", String;
    "profile", String;
    "profile_supported", Boolean;
    "document_digest", String;
    "authoring_status", Literals ["complete"; "incomplete"; "invalid"];
    "required_features", Many (String);
    "supported_features", Many (String);
    "unsupported_features", Many (String);
    "status", Literals ["declared_compatible"; "unsupported"];
    "target_status", Literals ["unassessed"; "unbound"];
    "schema_version", Literals ["biocompiler.policy_capability_assessment.v0.1"];
    "semantic_status", Literals ["unassessed"];
    "backend_execution", Literals ["not_performed"];
    "claim_scope", String];
  "Channel", [
    "id", String;
    "sender", Record "Ref";
    "recipients", Many (Record "Ref");
    "message_type", Record "TypeSpec";
    "contract", Record "DefinitionRef";
    "scope", Record "Scope";
    "ordering", Literals ["fifo"; "unordered"; "causal"];
    "loss", Literals ["permitted"; "forbidden"; "contract"];
    "duplication", Literals ["permitted"; "deduplicate"; "forbidden"];
    "acknowledgment", Literals ["none"; "required"];
    "retry", Literals ["none"; "bounded"; "contract"];
    "max_attempts", Union [Integer; Null];
    "latency", Union [Record "Quantity"; Null];
    "spatial_scope", Union [Record "Ref"; Null]];
  "ChassisProfile", [
    "id", String;
    "version", String;
    "lineage", String;
    "subtype", String;
    "activation_states", Many (String);
    "differentiation_states", Many (String);
    "capabilities", Many (Record "DefinitionRef");
    "operational_model", Record "DefinitionRef";
    "environment", Many (Record "DefinitionRef");
    "interfaces", Many (Record "DefinitionRef");
    "species", Literals ["human"];
    "recipient_class", Literals ["immune"; "immune_progenitor"]];
  "Clock", [
    "id", String;
    "basis", Literals ["availability"; "observation"; "logical"];
    "resolution", Record "Quantity";
    "simultaneous", Literals ["atomic_batch"]];
  "CompilationSubmission", [
    "request", Record "BuildRequest";
    "profile", String;
    "document_digest", String;
    "program_digest", String;
    "semantic_bundle", Record "DefinitionRef";
    "implementation_catalog", Record "DefinitionRef";
    "dependencies", Many (Record "DefinitionRef");
    "required_features", Many (String);
    "assumptions", Many (String);
    "outstanding_obligations", Many (String);
    "schema_version", Literals ["biocompiler.policy_submission.v0.1"];
    "authoring_status", Literals ["complete"];
    "semantic_status", Literals ["unassessed"];
    "target_status", Literals ["unassessed"];
    "backend_execution", Literals ["not_performed"];
    "claim_scope", String];
  "ContractClause", [
    "kind", Literals ["precondition"; "postcondition"; "transition"; "event"; "assumption"; "progress"; "resource"];
    "description", String;
    "expression", Union [Record "Expr"; Null]];
  "DefinitionRef", [
    "id", String;
    "version", String;
    "digest", String];
  "DeliveryContract", [
    "id", String;
    "intended_recipients", Many (Record "Ref");
    "arrival", Record "DefinitionRef";
    "expression", Record "DefinitionRef";
    "activation", Record "DefinitionRef";
    "co_delivery", Literals ["none_required"; "same_recipient"; "same_population"; "contract"];
    "contract", Record "DefinitionRef";
    "assumptions", Many (String)];
  "Deployment", [
    "id", String;
    "bindings", Many (Record "RoleBinding");
    "environment", Many (Record "DefinitionRef");
    "delivery", Record "DeliveryContract";
    "payload", Record "RNAConstraints";
    "route", Literals ["in_vivo"]];
  "Effect", [
    "id", String;
    "contract", Record "DefinitionRef";
    "executor", Record "Ref";
    "subject", Record "Ref";
    "lifecycle", Record "EffectLifecycle";
    "parameters", Many (Record "Argument");
    "spatial_scope", Union [Record "Ref"; Null];
    "relationship", Union [Record "DefinitionRef"; Null];
    "resources", Many (Record "DefinitionRef")];
  "EffectLifecycle", [
    "authorization", Literals ["initiation"; "continuous"];
    "on_loss", Literals ["continue"; "request_cancel"; "request_stop"];
    "on_unknown", Literals ["continue"; "request_cancel"; "request_stop"; "defer"];
    "cancellation", Literals ["unsupported"; "acknowledged"; "contract"];
    "completion", Literals ["feedback"; "contract"];
    "failure", Literals ["feedback"; "contract"];
    "contract", Record "DefinitionRef";
    "timeout", Union [Record "Quantity"; Null];
    "feedback_identity", Literals ["attempt_executor_subject"]];
  "Encounter", [
    "id", String;
    "executor", Record "Ref";
    "target", Record "Ref";
    "contract", Record "DefinitionRef";
    "termination", Literals ["contact_loss"; "explicit_event"; "contract"]];
  "Expr", [
    "op", Literals ["literal"; "observe"; "state"; "parameter"; "all"; "any"; "not"; "eq"; "ne"; "lt"; "le"; "gt"; "ge"; "add"; "subtract"; "multiply"; "divide"; "exists"; "forall"; "count"; "distinct"; "holds"; "recently"; "followed_by"; "within"; "after"; "until"; "rising"; "updated"; "effect_event"; "message_event"; "call"; "integrate"];
    "value_type", Record "TypeSpec";
    "args", Many (Record "Expr");
    "ref", Union [Record "Ref"; Null];
    "value", Union [String; Integer; Boolean; Record "Quantity"; Null];
    "scope", Union [Record "Ref"; Null];
    "contract", Union [Record "DefinitionRef"; Null];
    "duration", Union [Record "Quantity"; Null];
    "clock", Union [Record "Ref"; Null];
    "coverage", Union [Literals ["continuous"; "sampled"; "event"]; Null];
    "binding", Union [Record "Ref"; Null]];
  "Hole", [
    "id", String;
    "expected", String;
    "question", String];
  "ImplementationBinding", [
    "id", String;
    "version", String;
    "operation", Record "DefinitionRef";
    "realization", Record "DefinitionRef";
    "chassis", Many (String);
    "payload_formats", Many (Literals ["RNA"]);
    "dependencies", Many (Record "DefinitionRef");
    "evidence", Many (Record "DefinitionRef")];
  "ImplementationCatalogLock", [
    "id", String;
    "version", String;
    "implementations", Many (Record "ImplementationBinding")];
  "Machine", [
    "id", String;
    "executor", Record "Ref";
    "scope", Record "Scope";
    "states", Many (String);
    "initial", String;
    "terminal", Many (String);
    "lifetime", Literals ["encounter"; "executor"; "persistent"];
    "arbitration", Record "Arbitration"];
  "Message", [
    "id", String;
    "channel", Record "Ref";
    "sender", Record "Ref";
    "subject", Record "Ref";
    "correlation", Record "Ref";
    "payload", Record "Expr";
    "identity_policy", Literals ["per_emission_preserved_across_retries"]];
  "Observation", [
    "id", String;
    "observer", Record "Ref";
    "subject", Record "Ref";
    "value_type", Record "TypeSpec";
    "contract", Record "DefinitionRef";
    "clock", Record "Ref";
    "access", Literals ["cell"; "external_evaluator"];
    "coverage", Literals ["continuous"; "sampled"; "event"];
    "coherence", String;
    "freshness", Record "Quantity";
    "spatial_scope", Union [Record "Ref"; Null];
    "invalidity", Many (Literals ["missing"; "stale"; "invalid"; "conflicting"])];
  "Parameter", [
    "id", String;
    "value_type", Record "TypeSpec";
    "value", Union [String; Integer; Boolean; Record "Quantity"; Null];
    "lower", Union [Record "Quantity"; Null];
    "upper", Union [Record "Quantity"; Null];
    "selection", Literals ["fixed"; "design"; "measured"; "uncertain"]];
  "PolicyDraft", [
    "id", String;
    "semantics", Record "SemanticBundle";
    "declarations", Many (Union [Record "Role"; Record "Subject"; Record "Encounter"; Record "SpatialScope"; Record "Clock"; Record "Observation"; Record "StateStore"; Record "Effect"; Record "Rule"; Record "Machine"; Record "Transition"; Record "Channel"; Record "Message"; Record "Requirement"; Record "Parameter"]);
    "holes", Many (Record "Hole");
    "source_map", Many (Record "SourceSpan");
    "profile", String];
  "PolicyProgram", [
    "id", String;
    "semantics", Record "SemanticBundle";
    "declarations", Many (Union [Record "Role"; Record "Subject"; Record "Encounter"; Record "SpatialScope"; Record "Clock"; Record "Observation"; Record "StateStore"; Record "Effect"; Record "Rule"; Record "Machine"; Record "Transition"; Record "Channel"; Record "Message"; Record "Requirement"; Record "Parameter"]);
    "source_map", Many (Record "SourceSpan");
    "profile", String];
  "Quantity", [
    "amount", String;
    "unit", Record "Unit"];
  "RNAConstraints", [
    "design_count", Union [Integer; Null];
    "member_count", Union [Integer; Null];
    "helper_count", Union [Integer; Null];
    "copy_number", Union [Record "Parameter"; Null];
    "dose", Union [Record "Parameter"; Null];
    "orf_count", Union [Integer; Null];
    "product_count", Union [Integer; Null];
    "payload_persistence", Union [Record "Quantity"; Null];
    "effector_persistence", Union [Record "Quantity"; Null];
    "format", Literals ["RNA"]];
  "Ref", [
    "id", String;
    "kind", String];
  "Requirement", [
    "id", String;
    "kind", Literals ["safety"; "progress"; "bound"; "observability"; "external_control"; "approximation"; "assumption"; "preference"; "objective"];
    "description", String;
    "scope", Record "Scope";
    "condition", Union [Record "Expr"; Null];
    "response", Union [Record "Expr"; Null];
    "deadline", Union [Record "Quantity"; Null];
    "lower", Union [Record "Quantity"; Null];
    "upper", Union [Record "Quantity"; Null];
    "horizon", Union [Record "Quantity"; Literals ["unbounded_requested"]; Null];
    "assumptions", Many (String);
    "applies_to", Many (Record "Ref");
    "contract", Union [Record "DefinitionRef"; Null];
    "trigger", Union [Record "Expr"; Null];
    "clock", Union [Record "Ref"; Null]];
  "Role", [
    "id", String;
    "requires", Many (Record "DefinitionRef");
    "population", Union [Record "Ref"; Null];
    "lineage_role", Boolean];
  "RoleBinding", [
    "role", Record "Ref";
    "chassis", Record "ChassisProfile"];
  "Rule", [
    "id", String;
    "executor", Record "Ref";
    "on", Record "Expr";
    "when", Record "Expr";
    "unknown", Literals ["defer"; "transition"; "request_stop"];
    "effects", Many (Record "Ref");
    "assignments", Many (Record "Assignment");
    "arbitration", Union [Record "Arbitration"; Null];
    "unknown_target", Union [String; Null];
    "emissions", Many (Record "Ref")];
  "Scope", [
    "kind", Literals ["executor"; "encounter"; "target"; "population"; "lineage"; "region"; "program"];
    "subject", Union [Record "Ref"; Null]];
  "SemanticBundle", [
    "id", String;
    "version", String;
    "definitions", Many (Record "SemanticDefinition");
    "profile", String];
  "SemanticDefinition", [
    "id", String;
    "version", String;
    "category", Literals ["operation"; "capability"; "encounter"; "observation"; "lifecycle"; "environment"; "delivery"; "requirement"; "inheritance"; "resource"; "interface"; "spatial"; "transport"; "model"];
    "meaning", String;
    "parameters", Many (Record "Parameter");
    "result", Union [Record "TypeSpec"; Null];
    "clauses", Many (Record "ContractClause");
    "assumptions", Many (String);
    "executor_kind", Union [String; Null];
    "subject_kind", Union [String; Null]];
  "SourceSpan", [
    "declaration_id", String;
    "file", String;
    "line", Integer;
    "column", Integer;
    "pattern", Union [String; Null]];
  "SpatialScope", [
    "id", String;
    "kind", Literals ["contact"; "neighborhood"; "compartment"; "region"];
    "anchor", Record "Ref";
    "contract", Record "DefinitionRef";
    "radius", Union [Record "Quantity"; Null]];
  "StateStore", [
    "id", String;
    "value_type", Record "TypeSpec";
    "scope", Record "Scope";
    "initial", Union [String; Integer; Boolean; Record "Quantity"];
    "capacity", Union [Integer; Record "Ref"; Literals ["unbounded_requested"]];
    "overflow", Literals ["reject"; "saturate"; "evict_oldest"; "contract"];
    "lifetime", Literals ["encounter"; "executor"; "persistent"; "duration"];
    "reset", Union [Record "Expr"; Null];
    "inheritance", Literals ["reset"; "copy"; "partition"; "contract"; "not_applicable"];
    "duration", Union [Record "Quantity"; Null];
    "contract", Union [Record "DefinitionRef"; Null];
    "coordination", Union [Record "Ref"; Null]];
  "Subject", [
    "id", String;
    "entity_kind", Literals ["cell"; "population"; "region"; "compartment"; "lineage"];
    "identity", Literals ["encounter"; "stable"; "aggregate"; "bound"];
    "executor", Union [Record "Ref"; Null];
    "encounter", Union [Record "Ref"; Null];
    "domain", Union [Record "Ref"; Null]];
  "Transition", [
    "id", String;
    "machine", Record "Ref";
    "source", String;
    "destination", String;
    "on", Record "Expr";
    "when", Record "Expr";
    "unknown", Literals ["defer"; "transition"; "request_stop"];
    "effects", Many (Record "Ref");
    "assignments", Many (Record "Assignment");
    "unknown_target", Union [String; Null];
    "emissions", Many (Record "Ref")];
  "TypeSpec", [
    "kind", Literals ["truth"; "event"; "quantity"; "integer"; "text"; "entity"];
    "unit", Union [Record "Unit"; Null];
    "entity_kind", Union [String; Null]];
  "Unit", [
    "id", String;
    "dimension", String;
    "quantity_kind", String;
    "scale", String;
    "reference", Union [String; Null]];
]
let find name = List.assoc_opt name records
