"""Declare inspectable therapeutic policies; semantic execution is a later stage."""
from .model import (
    Record,
    SourceSpan,
    Hole,
    Ref,
    Unit,
    Quantity,
    TypeSpec,
    DefinitionRef,
    Expr,
    Parameter,
    ContractClause,
    SemanticDefinition,
    SemanticBundle,
    Scope,
    Role,
    Subject,
    Encounter,
    SpatialScope,
    Clock,
    Observation,
    StateStore,
    EffectLifecycle,
    Argument,
    Effect,
    Assignment,
    Arbitration,
    Rule,
    Machine,
    Transition,
    Channel,
    Message,
    Requirement,
    ChassisProfile,
    RoleBinding,
    DeliveryContract,
    RNAConstraints,
    Deployment,
    ImplementationBinding,
    ImplementationCatalogLock,
    AssuranceRequest,
    PolicyDraft,
    PolicyProgram,
    BuildRequest,
    PROFILE,
    TRUTH,
    EVENT,
    INTEGER,
    TEXT,
    Declaration,
    Document,
)
from .programs import AuthoringError, ProgramBuilder, ref
from .values import quantity, from_float, SECOND, MINUTE, COUNT, DIMENSIONLESS
from .logic import literal, all_of, any_of, not_, compare, arithmetic, exists, forall, count, distinct, entity, call, rising, TRUE, FALSE, UNKNOWN
from .serialization import load, loads, dump, dumps, to_data, from_data, document_digest, schema
from .validation import check, CheckReport, Diagnostic
from .inspection import inspect, diff, graph
from .model import CompilationSubmission, BackendCapabilities, CapabilityAssessment
from .handoff import prepare_submission, assess_capabilities, SubmissionError
from .serialization import PolicySerializationError, SerializationLimits
from . import logic, time, values, entities, chassis, observations, space, state, effects, behavior, coordination, requirements, deployment, catalog, patterns, typed, modules
from importlib import import_module as _import_module
from types import ModuleType as _ModuleType
from typing import TYPE_CHECKING as _TYPE_CHECKING

if _TYPE_CHECKING:
    from . import refinement, quantitative, quantitative_composition, module_linking, approximation, realization_evidence, quantitative_assurance

_OPTIONAL_NAMESPACES = frozenset({"refinement", "quantitative", "quantitative_composition", "module_linking",
                                 "approximation", "realization_evidence", "quantitative_assurance"})


def __getattr__(name: str) -> _ModuleType:
    if name not in _OPTIONAL_NAMESPACES:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return _import_module(f"{__name__}.{name}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | _OPTIONAL_NAMESPACES)

__all__ = [
    'Record',
    'SourceSpan',
    'Hole',
    'Ref',
    'Unit',
    'Quantity',
    'TypeSpec',
    'DefinitionRef',
    'Expr',
    'Parameter',
    'ContractClause',
    'SemanticDefinition',
    'SemanticBundle',
    'Scope',
    'Role',
    'Subject',
    'Encounter',
    'SpatialScope',
    'Clock',
    'Observation',
    'StateStore',
    'EffectLifecycle',
    'Argument',
    'Effect',
    'Assignment',
    'Arbitration',
    'Rule',
    'Machine',
    'Transition',
    'Channel',
    'Message',
    'Requirement',
    'ChassisProfile',
    'RoleBinding',
    'DeliveryContract',
    'RNAConstraints',
    'Deployment',
    'ImplementationBinding',
    'ImplementationCatalogLock',
    'AssuranceRequest',
    'PolicyDraft',
    'PolicyProgram',
    'BuildRequest',
    'PROFILE',
    'TRUTH',
    'EVENT',
    'INTEGER',
    'TEXT',
    'Declaration',
    'Document',
    'AuthoringError',
    'ProgramBuilder',
    'ref',
    'quantity',
    'from_float',
    'SECOND',
    'MINUTE',
    'COUNT',
    'DIMENSIONLESS',
    'literal',
    'all_of',
    'any_of',
    'not_',
    'compare',
    'arithmetic',
    'exists',
    'forall',
    'count',
    'distinct',
    'entity',
    'call',
    'rising',
    'TRUE',
    'FALSE',
    'UNKNOWN',
    'load',
    'loads',
    'dump',
    'dumps',
    'to_data',
    'from_data',
    'document_digest',
    'schema',
    'check',
    'CheckReport',
    'Diagnostic',
    'inspect',
    'diff',
    'graph',
    'CompilationSubmission',
    'BackendCapabilities',
    'CapabilityAssessment',
    'prepare_submission',
    'assess_capabilities',
    'SubmissionError',
    'PolicySerializationError',
    'SerializationLimits',
    'logic',
    'time',
    'values',
    'entities',
    'chassis',
    'observations',
    'space',
    'state',
    'effects',
    'behavior',
    'coordination',
    'requirements',
    'deployment',
    'catalog',
    'patterns',
    'typed',
    'modules',
    'refinement',
    'quantitative',
    'quantitative_composition',
    'module_linking',
    'approximation',
    'realization_evidence',
    'quantitative_assurance',
]
