#!/usr/bin/env python3
"""Freeze Python repr printability from checksum-pinned official Unicode 14 data.

Rebuild with --unicode-data <downloaded UnicodeData.txt> --write. Normal --check
is offline and checks the frozen table digest plus generated OCaml bytes. No host
Unicode database is consulted. The source file is available at SOURCE_URL.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLE = ROOT / "protocol/unicode14-printability.json"
MODULE = ROOT / "core/lib/domain/diagnostic_text.ml"
SOURCE_URL = "https://www.unicode.org/Public/14.0.0/ucd/UnicodeData.txt"
SOURCE_SHA256 = "36018e68657fdcb3485f636630ffe8c8532e01c977703d2803f5b89d6c5feafb"
PROFILE = "python_repr_unicode14.v1"
# Set from the reviewed official category data, not from Python's Unicode version.
RANGES_SHA256 = "3e6488250939c3c21d5fb1caeb5383c744b6c4a0f381b81cd48c057a61022087"


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def ranges_from_source(source):
    assert hashlib.sha256(source).hexdigest() == SOURCE_SHA256, "Wrong Unicode 14 source digest"
    ranges = [(32, 32)]
    pending = None
    for line in source.decode("utf-8").splitlines():
        fields = line.split(";")
        point, name, category = int(fields[0], 16), fields[1], fields[2]
        if name.endswith(", First>"):
            assert pending is None
            pending = (point, category)
        elif name.endswith(", Last>"):
            assert pending is not None and pending[1] == category
            if category[0] not in "CZ":
                ranges.append((pending[0], point))
            pending = None
        elif category[0] not in "CZ":
            ranges.append((point, point))
    assert pending is None
    merged = []
    for start, end in sorted(ranges):
        if merged and start <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], end)
        else:
            merged.append([start, end])
    return merged


def document(ranges):
    return {"schema_version": "biocompiler.unicode_printability.v1", "profile": PROFILE,
            "unicode_version": "14.0.0", "source_url": SOURCE_URL,
            "source_sha256": SOURCE_SHA256,
            "rule": "Printable iff Unicode General_Category is not C* or Z*, except U+0020 SPACE. Unassigned defaults to Cn.",
            "rule_source": "https://docs.python.org/3.11/library/stdtypes.html#str.isprintable",
            "repr_source": "https://github.com/python/cpython/blob/v3.11.0/Objects/unicodeobject.c",
            "license": "Unicode data files license: https://www.unicode.org/license.txt",
            "license_file": "protocol/UNICODE-LICENSE.txt",
            "attribution": "Derived from Unicode 14.0.0 UnicodeData.txt; Copyright 1991-2026 Unicode, Inc. Distributed under the retained Unicode License V3.",
            "ranges_sha256": hashlib.sha256(canonical(ranges).encode()).hexdigest(),
            "range_count": len(ranges), "printable_ranges": ranges}


def validate(data):
    ranges = data["printable_ranges"]
    assert data == document(ranges), "Changed Unicode profile/provenance"
    assert data["ranges_sha256"] == RANGES_SHA256, "Changed Unicode 14 printability ranges"
    previous = -2
    for start, end in ranges:
        assert type(start) is int and type(end) is int
        assert previous + 1 < start <= end <= 0x10FFFF
        previous = end


def native_module(data):
    ranges = "\n".join(f"  (0x{a:X}, 0x{b:X});" for a, b in data["printable_ranges"])
    return ('''(* Generated by tools/freeze_unicode14_printability.py from checksum-pinned
   Unicode 14.0.0 category data. Copyright 1991-2026 Unicode, Inc.
   See protocol/UNICODE-LICENSE.txt and protocol/unicode14-printability.json.
   Python repr diagnostics are versioned independently of semantic status. *)
open Bioc_wire
let profile = "python_repr_unicode14.v1"
let printable_ranges = [|
''' + ranges + '''
|]
let printable point =
  let rec search low high =
    if low > high then false
    else let middle = low + (high - low) / 2 in
      let first, last = printable_ranges.(middle) in
      if point < first then search low (middle - 1)
      else if point > last then search (middle + 1) high else true
  in search 0 (Array.length printable_ranges - 1)
let repr text =
  Diagnostic.require (String.length text <= Limits.max_string_bytes)
    "component_contract_limit" "Diagnostic text exceeds its native resource bound.";
  Json.validate_utf8 text;
  let quote = if String.contains text '\\'' && not (String.contains text '"') then '"' else '\\'' in
  let result = Buffer.create (String.length text + 2) in
  Buffer.add_char result quote;
  let position = ref 0 in
  let byte index = Char.code text.[index] in
  while !position < String.length text do
    let start = !position in
    let first = byte start in
    let width, point =
      if first < 0x80 then 1, first
      else if first < 0xE0 then 2, ((first land 0x1F) lsl 6) lor (byte (start + 1) land 0x3F)
      else if first < 0xF0 then 3, ((first land 0x0F) lsl 12) lor ((byte (start + 1) land 0x3F) lsl 6) lor (byte (start + 2) land 0x3F)
      else 4, ((first land 7) lsl 18) lor ((byte (start + 1) land 0x3F) lsl 12) lor ((byte (start + 2) land 0x3F) lsl 6) lor (byte (start + 3) land 0x3F) in
    if point = Char.code quote || point = 0x5C then (
      Buffer.add_char result '\\\\'; Buffer.add_char result (Char.chr point))
    else if point = 10 then Buffer.add_string result "\\\\n"
    else if point = 13 then Buffer.add_string result "\\\\r"
    else if point = 9 then Buffer.add_string result "\\\\t"
    else if printable point then Buffer.add_substring result text start width
    else if point <= 0xFF then Buffer.add_string result (Printf.sprintf "\\\\x%02x" point)
    else if point <= 0xFFFF then Buffer.add_string result (Printf.sprintf "\\\\u%04x" point)
    else Buffer.add_string result (Printf.sprintf "\\\\U%08x" point);
    Diagnostic.require (Buffer.length result <= Limits.max_string_bytes)
      "component_contract_limit" "Escaped diagnostic text exceeds its native resource bound.";
    position := start + width
  done;
  Buffer.add_char result quote;
  Diagnostic.require (Buffer.length result <= Limits.max_string_bytes)
    "component_contract_limit" "Escaped diagnostic text exceeds its native resource bound.";
  Buffer.contents result
''').encode()


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--unicode-data", type=Path)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--write", action="store_true")
    modes.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.unicode_data:
        data = document(ranges_from_source(args.unicode_data.read_bytes()))
    else:
        if args.write:
            parser.error("--write requires checksum-pinned --unicode-data")
        data = json.loads(TABLE.read_text())
    validate(data)
    table = (json.dumps(data, sort_keys=True, indent=2) + "\n").encode()
    native = native_module(data)
    if args.write:
        TABLE.write_bytes(table); MODULE.write_bytes(native)
    else:
        assert TABLE.read_bytes() == table, "Stale Unicode 14 table"
        assert MODULE.read_bytes() == native, "Stale native Unicode diagnostic implementation"
    print(json.dumps({"profile": PROFILE, "ranges": data["range_count"], "status": "written" if args.write else "checked"}))


if __name__ == "__main__":
    main()
