"""Independent artificial asymmetric reservoir and exact RNA premises; no native execution."""
from __future__ import annotations

import argparse
from copy import deepcopy
from dataclasses import replace
import hashlib
import json
from pathlib import Path

from biocompiler import policy as p
try:
    import generate_policy_finite_machine_fixture as finite
except ModuleNotFoundError:
    from tools import generate_policy_finite_machine_fixture as finite

shared = finite.shared
ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "core/test/data/policy_quantitative_step_v01.json"
PROFILE = "biocompiler.policy_sampled_step_reservoir_component_mrna.v0.1"
PRIMITIVE = "biocompiler.policy_multi_site_implementation.v0.1"
OBSERVABLE = "biocompiler.policy_multi_site_observables.v0.1"
PHASE = "biocompiler.policy_multi_site_primitive_execution.v0.1"
STATES = ["q0", "q1", "q2", "q3", "q4"]
LEVELS = ["0", "1", "2", "3", "4"]
# Literal state rows are independent premises, not generated by the authoring law.
ROWS = (("q0", "q2", "q0", False), ("q1", "q3", "q0", True),
        ("q2", "q4", "q1", True), ("q3", "q4", "q2", False), ("q4", "q4", "q3", False))
SPEC = {"id": "sampled_step_reservoir", "states": STATES, "terminal": [], "effects": ["response"],
    "transitions": [(identity, source, destination, "updated", guard, effect)
        for identity, source, destination, guard, effect in (
            ("up0", "q0", "q2", "positive", None), ("down0", "q0", "q0", "negative", None),
            ("up1", "q1", "q3", "positive", "response"), ("down1", "q1", "q0", "negative", None),
            ("up2", "q2", "q4", "positive", "response"), ("down2", "q2", "q1", "negative", None),
            ("up3", "q3", "q4", "positive", None), ("down3", "q3", "q2", "negative", None),
            ("up4", "q4", "q4", "positive", None), ("down4", "q4", "q3", "negative", None))]}


def law():
    return {"schema_version": "biocompiler.policy_sampled_reservoir.v0.2",
        "profile": "biocompiler.policy_sampled_saturating_step_reservoir.v0.1",
        "substance": "fixture.reservoir.amount", "compartment": "fixture.executor.reservoir", "unit": p.to_data(p.COUNT),
        **{key: p.to_data(p.quantity(amount, p.COUNT)) for key, amount in (
            ("quantum", "1"), ("capacity", "4"), ("threshold", "3"), ("initial", "0"), ("rise", "2"), ("fall", "1"))},
        "sample_period": p.to_data(p.quantity(1, p.SECOND))}


coalesce_output_boundaries = finite.coalesce_output_boundaries

def declared_fragments():
    """Supply two distinct commit ports feeding one attempt store, with per-site guards."""
    library, fragments, links = finite.declared_fragments(SPEC)
    library["profile"] = PRIMITIVE
    for model in library["models"]:
        body = model["body"]
        if body["primitive"] == "evidence_bank": body["configuration"]["freshness_ticks"] = 1
        if body["primitive"] == "machine_bank": body["configuration"]["initial"] = "q0"
        if body["primitive"] == "attempt_bank":
            body.update(primitive="attempt_bank_sites", profile=PRIMITIVE)
            body["configuration"].update(sites=2, capacity=6)
        model["identity"]["content_fingerprint"] = shared.digest(body)
        model["configuration_digest"] = shared.digest(body["configuration"])
    models = {row["identity"]["id"]: row for row in library["models"]}
    for fragment in fragments.values():
        fragment.update(profile="biocompiler.policy_multi_site_fragment.v0.1", primitive_profile=PRIMITIVE,
                        observable_profile=OBSERVABLE, phase_profile=PHASE)
        for node in fragment["nodes"]: node["model"] = deepcopy(models[node["model"]["identity"]["id"]])
        seen = {}
        for boundary in fragment["boundary_ports"]:
            identity = boundary["id"]
            index = seen.get(identity, 0)
            seen[identity] = index + 1
            boundary["id"] = identity + str(index)
            if fragment is fragments["actuator"] and identity != "response.product":
                boundary["endpoint"]["port"] += str(index)
    seen = {}
    for link in links:
        identity = link["id"]
        index = seen.get(identity, 0)
        seen[identity] = index + 1
        link["id"] = identity + str(index)
        for end in ("producer", "consumer"): link[end]["boundary"] += str(index)
    coalesce_output_boundaries(fragments, links)
    return library, fragments, links


def build():
    seed_bytes = (shared.DATA / "policy_staged_material_seed_v01.json").read_bytes()
    assert hashlib.sha256(seed_bytes).hexdigest() == shared.SEED_SHA256
    seed = json.loads(seed_bytes)
    library, fragments, links = declared_fragments()
    original = finite.implementation_request(SPEC, library)
    original.update(schema_version="biocompiler.policy_realization_request.v0.7", profile="biocompiler.policy_multi_site_inputs.v0.1")
    document = p.from_data(original["document"], p.BuildRequest)
    declarations = tuple(replace(row, initial="q0") if isinstance(row, p.Machine) else
        replace(row, freshness=p.quantity(1, p.SECOND)) if isinstance(row, p.Observation) else
        replace(row, horizon=p.quantity(16, p.SECOND)) if isinstance(row, p.Requirement) else row
        for row in document.program.declarations)
    document = replace(document, program=replace(document.program, declarations=declarations),
                       assurance=replace(document.assurance, horizon=p.quantity(16, p.SECOND)))
    original["document"] = p.to_data(document)
    domain = original["operating_domain"]
    domain.update(horizon_ticks=16, observation_factors=[], feedback_factors=[], foreign_feedback_factors=[])
    domain["logical_limits"]["max_source_attempts"] = 6
    domain["lifecycle_factors"] = [{"slots": ["e1", "e2"], "ticks": [12], "actions": ["keep", "reset"]}]
    domain["fixed_observations"] = [{"available_tick": tick, "observed_tick": tick, "observation": "condition", "slot": slot,
        "status": "missing" if value is None else "valid", "value": value}
        for tick, value in ((0, False), (1, True), (2, True), (3, None), (4, False), (5, False),
                            (7, False), (8, True), (9, True), (10, True), (11, False), (12, False),
                            (13, True), (14, True), (15, False)) for slot in ("e1", "e2")]
    components, rule, union, molecule = finite.composition(SPEC, fragments, links, seed)
    for component in components.values():
        # Same bounded active-attempt storage, explicit new primitive identity.
        requirements = deepcopy(component["body"]["fragment"])
        for node in requirements["nodes"]:
            if node["model"]["body"]["primitive"] == "attempt_bank_sites":
                node["model"]["body"]["primitive"] = "attempt_bank"
        component["body"]["provider_requirements"] = shared.prerequisites(requirements)
        for requirement in component["body"]["provider_requirements"]:
            if requirement.get("unit") == "machine_state_bits": requirement["minimum"] = 3
            if requirement.get("unit") in ("active_attempt_records", "timer_cells") and requirement["owner"]["id"] == "response":
                requirement["minimum"] = 6
    component = components["control"]
    local = {node["id"]: node["model"]["identity"] for node in fragments["control"]["nodes"]}
    component.update(schema_version="biocompiler.policy_component_material.v0.3", profile="biocompiler.policy_step_quantitative_local_material.v0.1")
    component["body"]["quantitative_contracts"] = [{"id": "reservoir", "mechanism": law(),
        "state": {"node": "machine", "model": local["machine"], "values": [
            {"state": state, "quantity": p.to_data(p.quantity(amount, p.COUNT))} for state, amount in zip(STATES, LEVELS)]},
        "input": {"node": "evidence", "model": local["evidence"], "value_port": "value", "updated_port": "updated"},
        "outputs": [{"source_state": "q1", "input": True, "boundary": "response.request0", "model": local["commit2"]},
                    {"source_state": "q2", "input": True, "boundary": "response.request1", "model": local["commit4"]}]}]
    for component in components.values(): component["identity"]["content_fingerprint"] = shared.digest(component["body"])
    rule.update(schema_version="biocompiler.policy_component_assembly_rule.v0.5",
                profile="biocompiler.policy_multi_site_component_assembly.v0.1")
    rule["body"].update(primitive_profile=PRIMITIVE, observable_profile=OBSERVABLE, phase_profile=PHASE)
    rule["body"]["components"] = [{"slot": slot, "component": component["identity"]} for slot, component in components.items()]
    rule["identity"]["content_fingerprint"] = shared.digest(rule["body"])
    union.update(primitive_profile=PRIMITIVE, observable_profile=OBSERVABLE, phase_profile=PHASE)
    context, inputs, resources = finite.context(SPEC, original, components, rule, union)
    context["record_layout"].update(horizon_ticks=16, maximum_tick=18, attempts=6)
    layout_digest = shared.digest(context["record_layout"])
    def extend_availability(value):
        if isinstance(value, dict):
            if "duration_min" in value and "duration_max" in value: value.update(duration_min="16", duration_max="16")
            for child in value.values(): extend_availability(child)
        elif isinstance(value, list):
            for child in value: extend_availability(child)
    for provider in context["providers"]:
        extend_availability(provider["body"])
        for capacity in provider["body"]["capacities"]:
            capacity["record_layout_digest"] = layout_digest
            if capacity["unit"] == "evidence_records": capacity["quantity"] = 17
        provider["identity"]["content_fingerprint"] = shared.digest(provider["body"])
    bridge = original["catalog_bindings"][0]
    request = {"schema_version": "biocompiler.policy_component_material_request.v0.10", "profile": PROFILE,
        "implementation_request": original,
        "component_library": {"schema_version": "biocompiler.policy_component_library.v0.1",
            "profile": "biocompiler.policy_exact_component_library.v0.1", "components": list(components.values())},
        "composition_rule": rule, "catalog_binding": {**{key: bridge[key] for key in ("entry_id", "entry_version", "entry_digest", "operation", "realization")},
            "components": rule["body"]["components"], "rule": rule["identity"]},
        "input_bindings": inputs, "resource_bindings": resources, "context": context,
        "budgets": {"profile": "biocompiler.policy_component_material_resources.v0.1", "max_work": 500000000,
            "max_report_bytes": 8323072, "max_report_nodes": 249968},
        "quantitative": {"mechanism": law(), "selection": {"instance": "control", "component": deepcopy(components["control"]["identity"]), "contract": "reservoir"},
            "source": {"machine": "machine", "observation": "condition", "effect": "response"}}}
    table = [{"source": state, "input": truth, "destination": destination, "request": requested}
        for state, positive, negative, requested in ROWS
        for truth, destination, requested in (("true", positive, requested), ("false", negative, False), ("unknown", state, False))]
    limits = shared.original()["limits"]
    limits["source"]["max_ticks"] = 17
    limits["candidate"]["max_work"] = 10_000_000
    return {"schema_version": "biocompiler.policy_quantitative_step_literals.v0.1",
        "notice": "Artificial supplied asymmetric quantitative component-to-RNA premises. No native acceptance or biological evidence is asserted.",
        "seed_sha256": shared.SEED_SHA256, "request": request, "limits": limits,
        "expected": {"molecule": molecule, "sequence": "CCAUGGCUUAAGGAAAA", "ordered_union": union, "table": table,
            "states": STATES, "levels": LEVELS, "crossing_transitions": ["up1", "up2"], "crossing_commits": ["commit2", "commit4"],
            "keep_trajectory": [0, 2, 4, 4, 3, 2, 2, 1, 3, 4, 4, 3, 2, 4, 4, 3, 3],
            "reset_trajectory": [0, 2, 4, 4, 3, 2, 2, 1, 3, 4, 4, 3, 0, 2, 4, 3, 3]}}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    encoded = json.dumps(build(), sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False) + "\n"
    assert len(encoded.encode()) < 1_000_000, "Keep supplied originals bounded"
    if args.check: assert PATH.read_text() == encoded, "Step quantitative fixture changed; review original premises"
    else: PATH.write_text(encoded)


if __name__ == "__main__": main()
