"""Generate the closed OCaml representation schema from reviewed Python records.

This development-only tool never runs in the compiler. Its output describes
field shapes and literal alternatives only, not policy semantic acceptance.
"""
from __future__ import annotations

import argparse
from dataclasses import fields
import hashlib
import json
from pathlib import Path
import sys
import types
from typing import Literal, Union, get_args, get_origin, get_type_hints

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from biocompiler.policy import model


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def shape(hint: object) -> str:
    origin, args = get_origin(hint), get_args(hint)
    if origin in (Union, types.UnionType):
        return "Union [" + "; ".join(shape(item) for item in args) + "]"
    if origin is Literal:
        if not all(type(item) is str for item in args):
            raise TypeError("Policy literals must be exact strings")
        return "Literals [" + "; ".join(quoted(item) for item in args) + "]"
    if origin is tuple:
        if len(args) == 2 and args[1] is Ellipsis:
            return "Many (" + shape(args[0]) + ")"
        return "Tuple [" + "; ".join(shape(item) for item in args) + "]"
    primitives = {str: "String", int: "Integer", bool: "Boolean", type(None): "Null"}
    if hint in primitives:
        return primitives[hint]
    if hint in model.REGISTRY.values():
        return "Record " + quoted(hint.__name__)
    raise TypeError(f"Unsupported schema annotation: {hint!r}")


def render() -> str:
    digest = hashlib.sha256((ROOT / "src/biocompiler/policy/model.py").read_bytes()).hexdigest()
    lines = [
        "(* Generated by tools/generate_policy_wire_schema.py; do not edit by hand.",
        "   Closed representation data only; no semantic acceptance authority. *)",
        'let model_sha256 = "' + digest + '"',
        "type shape = String | Integer | Boolean | Null | Literals of string list",
        "  | Record of string | Many of shape | Tuple of shape list | Union of shape list",
        "let records = [",
    ]
    for name, kind in sorted(model.REGISTRY.items()):
        hints = get_type_hints(kind)
        members = ";\n    ".join(quoted(item.name) + ", " + shape(hints[item.name]) for item in fields(kind))
        lines.append("  " + quoted(name) + ", [\n    " + members + "];" )
    lines.extend([
        "]", "let find name = List.assoc_opt name records", "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "core/lib/domain/policy_schema.ml"
    expected = render()
    if args.check:
        if not target.exists() or target.read_text() != expected:
            print("Closed policy schema differs from reviewed model; regenerate and review.", file=sys.stderr)
            return 1
        print(f"Policy wire schema matches {len(model.REGISTRY)} closed record definitions.")
        return 0
    target.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
